export enum ROUTES {
    HOME = "/",
    SIGN_UP = "/sign-up",
    SIGN_IN = "/sign-in",
    PRIVACY_POLICY = "/privacy-policy",
    TERMS_AND_CONDITIONS = "/terms-and-conditions",
    DASHBOARD = "/dashboard",
    EXPLORE = "/explore",
    CONTRIBUTE = "/contribute",
    ABOUT = "/about",
    ABOUT_US = `${ABOUT}/about-us`,
    ABOUT_TEAM = `${ABOUT_US}/team`,
    ABOUT_REWARDS = `${ABOUT}/rewards`,
    ABOUT_REWARDS_HOW_TO_GET_PAID = `${ABOUT_REWARDS}/how-to-get-paid`,
}
